spring:
  application:
    name: CONFIG-Prod
  cloud:
    config:
      server:
        bootstrap: true
        git:
          uri: https://github.com/hardik10553/microservice-tutorial-config
          clone-on-start: true
